title: LOLWeb

url: https://l0lweb.github.io

exclude:
  - /CNAME
  - /Dockerfile
  - /Gemfile*
  - /LICENSE
  - /Makefile
  - /README.md
  - /_private/
  - /linter/
  - /vendor/

permalink: pretty

collections:
  lolwebs:
    output: true

defaults:
  - scope:
      path: _lolwebs
    values:
      layout: lolweb
      title: ""
